// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/mmaruf23/golang-rest-api/config"
	"github.com/mmaruf23/golang-rest-api/internal/app"
	"github.com/mmaruf23/golang-rest-api/internal/controller"
	"github.com/mmaruf23/golang-rest-api/internal/middleware"
	"github.com/mmaruf23/golang-rest-api/internal/repository"
	"github.com/mmaruf23/golang-rest-api/internal/service"
	"net/http"
)

// Injectors from injector.go:

func InitializeServer(appConfig *config.AppConfig) *http.Server {
	categoryRepositoryImpl := repository.NewCategoryRepositoryImpl()
	db := app.NewMySQLConnection(appConfig)
	validate := app.NewValidator()
	categoryServiceImpl := service.NewCategoryService(categoryRepositoryImpl, db, validate)
	categoryControllerImpl := controller.NewCategoryController(categoryServiceImpl)
	router := app.NewRouter(categoryControllerImpl)
	authMiddleware := middleware.NewAuthMiddleware(router)
	server := NewServer(authMiddleware)
	return server
}

// injector.go:

var categorySet = wire.NewSet(repository.NewCategoryRepositoryImpl, wire.Bind(new(repository.CategoryRepository), (new(*repository.CategoryRepositoryImpl))), service.NewCategoryService, wire.Bind(new(service.CategoryService), (new(*service.CategoryServiceImpl))), controller.NewCategoryController, wire.Bind(new(controller.CategoryController), (new(*controller.CategoryControllerImpl))))
